Miljan/feature/mmd 1934 ux UI audit
mxc-foundation/mxc-shared-flutter pull request #35
Opened 2021-12-03 17:26 UTC by miljan-mxc

2021-12-03 17:28 UTC, rtviwe submitted a review, later dismissed

2021-12-03 17:28 UTC, festelo commented on logic/lib/src/domain/features/auth/auth_use_case.dart
> +  Future<bool> authenticateWeChatUser(
better to move it into sign_in_wechat_use_case.
We don't need this method in shared library, because wechat sign-in will only be used from datadash app. (it will just not work with  web)

2021-12-03 17:43 UTC, miljan-mxc commented on logic/lib/src/domain/features/auth/auth_use_case.dart
> +  Future<bool> authenticateWeChatUser(
good point. moved

2021-12-03 17:48 UTC, festelo requested changes

2021-12-03 17:48 UTC, festelo commented on ui/lib/src/theme/images.dart
> +        package: _packageName,
change to `mxcUiPackageName`, i changed the name because i needed to make the field public.

2021-12-03 18:17 UTC, miljan-mxc commented on ui/lib/src/theme/images.dart
> +        package: _packageName,
changed

2021-12-06 10:21 UTC, festelo approved these changes

2021-12-06 10:21 UTC, merged